require("spec.bootstrap")

local game_driver = require("tools.acceptance.game_driver")

describe("game_driver", function()
  describe("new_game", function()
    it("returns a context with a real game instance", function()
      local ctx = game_driver.new_game()
      assert.is_table(ctx)
      assert.is_table(ctx.game)
      assert.is_table(ctx.game.players)
      assert.is_true(#ctx.game.players >= 2)
    end)

    it("creates players starting at position 1", function()
      local ctx = game_driver.new_game()
      local player = ctx.game.players[1]
      assert.are.equal(1, player.position)
    end)

    it("provides outer_ring_size", function()
      local ctx = game_driver.new_game()
      assert.are.equal(32, ctx.outer_ring_size)
    end)
  end)

  describe("current_player", function()
    it("returns the first player", function()
      local ctx = game_driver.new_game()
      local player = game_driver.current_player(ctx)
      assert.are.equal(ctx.game.players[1], player)
    end)
  end)

  describe("set_player_position", function()
    it("updates player position via game API", function()
      local ctx = game_driver.new_game()
      local player = game_driver.current_player(ctx)
      game_driver.set_player_position(ctx, player, 10)
      assert.are.equal(10, player.position)
    end)
  end)

  describe("move", function()
    it("moves player forward using rules.movement.move", function()
      local ctx = game_driver.new_game()
      local player = game_driver.current_player(ctx)
      local result = game_driver.move(ctx, player, 3)
      assert.are.equal(4, player.position)
      assert.are.equal(0, result.passed_start)
      assert.are.equal(3, #result.visited)
    end)

    it("tracks pass-start when wrapping around outer ring", function()
      local ctx = game_driver.new_game()
      local player = game_driver.current_player(ctx)
      game_driver.set_player_position(ctx, player, 30)
      game_driver.clear_move_state(ctx, player)
      local result = game_driver.move(ctx, player, 5)
      assert.are.equal(1, result.passed_start)
    end)
  end)

  describe("set_next_rolls", function()
    it("queues deterministic dice results", function()
      local ctx = game_driver.new_game()
      game_driver.set_next_rolls(ctx, {3, 5, 7})
      assert.are.equal(3, ctx.game.rng:next_int(1, 6))
      assert.are.equal(5, ctx.game.rng:next_int(1, 6))
      assert.are.equal(7, ctx.game.rng:next_int(1, 6))
    end)
  end)

  describe("player_position", function()
    it("returns current player position", function()
      local ctx = game_driver.new_game()
      local player = game_driver.current_player(ctx)
      game_driver.set_player_position(ctx, player, 15)
      assert.are.equal(15, game_driver.player_position(ctx, player))
    end)
  end)

  describe("player_cash", function()
    it("returns player balance via game API", function()
      local ctx = game_driver.new_game()
      local player = game_driver.current_player(ctx)
      local cash = game_driver.player_cash(ctx, player)
      assert.is_number(cash)
      assert.is_true(cash > 0)
    end)
  end)
end)
