repos:
  - repo: local
    hooks:
      - id: lua-deps-check
        name: lua deps_check
        entry: lua tests/deps_check.lua
        language: system
        pass_filenames: false
      - id: lua-regression
        name: lua regression
        entry: lua tests/regression.lua
        language: system
        pass_filenames: false
