local item_ids = require("src.config.gameplay.item_ids")

describe("choices_market", function()
  it("_test_market_context_entry_name_vehicle_cfg", function()
    local context = require("src.rules.market.query.context")
    local name = context.entry_name({ kind = "vehicle", product_id = 5001 })
    assert(type(name) == "string" and name ~= "", "vehicle entry should resolve configured vehicle name")
  end)

  it("_test_market_context_entry_name_item_cfg_and_fallback", function()
    local context = require("src.rules.market.query.context")
    local configured = context.entry_name({ kind = "item", product_id = item_ids.free_rent })
    local fallback = context.entry_name({ kind = "item", product_id = 999999, name = "FallbackName" })
    assert(type(configured) == "string" and configured ~= "", "item entry should resolve configured item name")
    assert(fallback == "FallbackName", "unknown item should fallback to entry.name")
  end)
end)
