describe("suites.domain.test_profiles_crap_coverage", function()
  it("suite load failed: ...ted/./spec/suites/domain/test_profiles_crap_coverage.lua:3: attempt to index a nil value (field '_M_test')", function()
    pending("suite load failed: src.config.testing.test_profiles._M_test is unavailable")
  end)
end)
