-- Achievement catalog exported from the Eggy editor project save
-- (archives.mm, zstd+MessagePack) by tools/ops/export_achievements.py.
-- No runtime needed; regenerate after editing achievements in the editor.
-- Progress tracking / unlock delivery stay host-owned
-- (see src/app/host_integrations/achievement.lua).
return {
  { id = 1, category = "简单", name = "最强大富翁I", description = "胜出还不是轻而易举？", condition = "获得1场游戏的胜利", target_progress = 1 },
  { id = 2, category = "普通", name = "最强大富翁II", description = "买下3个地块", condition = "获得3场游戏的胜利", target_progress = 3 },
  { id = 3, category = "困难", name = "最强大富翁III", description = "胜出还不是轻而易举？", condition = "获得5场游戏的胜利", target_progress = 5 },
  { id = 4, category = "传奇", name = "最强大富翁IIII", description = "默认描述", condition = "", target_progress = 10 },
  { id = 5, category = "简单", name = "大地主I", description = "地越多越好", condition = "买下3个地块", target_progress = 3 },
  { id = 6, category = "简单", name = "大地主II", description = "地越多越好", condition = "买下6个地块", target_progress = 6 },
  { id = 7, category = "困难", name = "大地主III", description = "地越多越好", condition = "买下10个地块", target_progress = 10 },
  { id = 8, category = "传奇", name = "大地主IIII", description = "地越多越好", condition = "买下15个地块", target_progress = 15 },
  { id = 9, category = "简单", name = "做梦都会笑I", description = "收钱做梦都会笑", condition = "累计收取1000金币", target_progress = 1000 },
  { id = 10, category = "普通", name = "做梦都会笑II", description = "默认描述", condition = "累计收取3000金币", target_progress = 3000 },
  { id = 11, category = "困难", name = "做梦都会笑III", description = "收钱做梦都会笑", condition = "累计收取5000金币", target_progress = 5000 },
  { id = 12, category = "传奇", name = "做梦都会笑IIII", description = "收钱做梦都会笑", condition = "累计收取10000金币", target_progress = 10000 },
  { id = 13, category = "简单", name = "纳税大户I", description = "唯有税收与死亡不可避免", condition = "累计交税30000金币", target_progress = 30000 },
  { id = 14, category = "普通", name = "纳税大户II", description = "唯有税收与死亡不可避免", condition = "累计交税60000金币", target_progress = 60000 },
  { id = 15, category = "困难", name = "纳税大户III", description = "唯有税收与死亡不可避免", condition = "累计交税80000金币", target_progress = 80000 },
  { id = 16, category = "传奇", name = "纳税大户IIII", description = "唯有税收与死亡不可避免", condition = "累计交税100000金币", target_progress = 100000 },
  { id = 17, category = "简单", name = "道具达人I", description = "有人要倒霉咯！", condition = "累计使用3张道具卡", target_progress = 3 },
  { id = 18, category = "普通", name = "道具达人II", description = "有人要倒霉咯！", condition = "累计使用6张道具卡", target_progress = 6 },
  { id = 19, category = "困难", name = "道具达人III", description = "有人要倒霉咯！", condition = "累计使用10张道具卡", target_progress = 10 },
  { id = 20, category = "传奇", name = "道具达人IIII", description = "有人要倒霉咯！", condition = "累计使用15张道具卡", target_progress = 15 },
  { id = 21, category = "简单", name = "把握机会I", description = "爱拼才会赢！", condition = "累计抽到3张机会卡", target_progress = 3 },
  { id = 22, category = "普通", name = "把握机会II", description = "爱拼才会赢！", condition = "累计抽到6张机会卡", target_progress = 6 },
  { id = 23, category = "困难", name = "把握机会III", description = "爱拼才会赢！", condition = "累计抽到10张机会卡", target_progress = 10 },
  { id = 24, category = "传奇", name = "把握机会IIII", description = "爱拼才会赢！", condition = "累计抽到15张机会卡", target_progress = 15 },
  { id = 25, category = "简单", name = "黑市常客I", description = "得黑市者得天下！", condition = "累计在黑市购买1件道具", target_progress = 1 },
  { id = 26, category = "普通", name = "黑市常客II", description = "得黑市者得天下！", condition = "累计在黑市购买3件道具", target_progress = 3 },
  { id = 27, category = "困难", name = "黑市常客III", description = "得黑市者得天下！", condition = "累计在黑市购买6件道具", target_progress = 6 },
  { id = 28, category = "简单", name = "黑市常客IIII", description = "得黑市者得天下！", condition = "累计在黑市购买·0件道具", target_progress = 10 },
  { id = 29, category = "简单", name = "小平房", description = "盖楼好收钱", condition = "加盖1座1级建筑", target_progress = 1 },
  { id = 30, category = "困难", name = "小别墅", description = "盖楼好收钱", condition = "加盖1座2级建筑", target_progress = 1 },
  { id = 31, category = "简单", name = "大楼房", description = "盖楼好收钱", condition = "加盖1座3级建筑", target_progress = 1 },
  { id = 32, category = "隐藏", name = "福神降临", description = "福星高照", condition = "被福神附身1次", target_progress = 1 },
  { id = 33, category = "隐藏", name = "财神降临", description = "财运亨通", condition = "被财神附身1次", target_progress = 1 },
  { id = 34, category = "隐藏", name = "穷神降临", description = "人穷志不短", condition = "被穷神附身1次", target_progress = 1 },
  { id = 35, category = "隐藏", name = "药到病除", description = "我还能再抢救一下", condition = "被送进医院1次", target_progress = 1 },
  { id = 36, category = "隐藏", name = "迷失深山", description = "哪里？这是哪里？", condition = "被送进深山1次", target_progress = 1 },
  { id = 37, category = "隐藏", name = "连田阡陌", description = "这条街都是我的！", condition = "获得3个连续的地块。", target_progress = 1 },
  { id = 38, category = "隐藏", name = "哥斯拉？", description = "为什么会有哥斯拉？", condition = "被怪兽拆除1次你的房屋", target_progress = 1 },
  { id = 39, category = "隐藏", name = "风神过境！", description = "全是豆腐渣工程！", condition = "被台风拆除1次你的房屋", target_progress = 1 },
  { id = 40, category = "传奇", name = "小猪佩奇！", description = "我们不一样", condition = "使用小猪佩奇皮肤1次", target_progress = 1 },
  { id = 41, category = "传奇", name = "小猪乔治！", description = "我们不一样", condition = "使用小猪乔治皮肤1次", target_progress = 1 },
  { id = 42, category = "传奇", name = "海绵宝宝！", description = "我们不一样", condition = "使用海绵宝宝皮肤1次", target_progress = 1 },
  { id = 43, category = "传奇", name = "派大星！", description = "我们不一样", condition = "使用派大星皮肤1次", target_progress = 1 },
  { id = 44, category = "传奇", name = "奶龙？奶龙！", description = "我们不一样", condition = "使用奶龙皮肤1次", target_progress = 1 },
  { id = 45, category = "传奇", name = "水豚嘟嘟", description = "我们不一样", condition = "使用水豚嘟嘟皮肤1次", target_progress = 1 },
}
