local constants = {
  turn_limit = 1000,
  item_phase_queue = { "pre_action", "pre_move", "post_action" },
  item_ids = {
    free_rent = 2001,
    remote_dice = 2002,
    dice_multiplier = 2003,
    roadblock = 2004,
    mine = 2005,
    clear_obstacles = 2006,
    steal = 2007,
    monster = 2008,
    strong = 2009,
    tax_free = 2010,
    share_wealth = 2011,
    exile = 2012,
    missile = 2013,
    tax = 2014,
    invite_deity = 2015,
    send_poor = 2016,
    rich = 2017,
    poor = 2018,
    angel = 2019,
  },
  store_path_enum = {
    players = 1,
    status = 2,
    seat_id = 3,
    eliminated = 4,
    properties = 5,
    inventory = 6,
    position = 7,
    board = 8,
    tiles = 9,
    owner_id = 10,
    level = 11,
    turn = 12,
    action_anim_seq = 13,
    action_anim = 14,
    current_player_index = 15,
    pending_choice = 16,
  },
}

constants.store_path_key = {
  [constants.store_path_enum.players] = "players",
  [constants.store_path_enum.status] = "status",
  [constants.store_path_enum.seat_id] = "seat_id",
  [constants.store_path_enum.eliminated] = "eliminated",
  [constants.store_path_enum.properties] = "properties",
  [constants.store_path_enum.inventory] = "inventory",
  [constants.store_path_enum.position] = "position",
  [constants.store_path_enum.board] = "board",
  [constants.store_path_enum.tiles] = "tiles",
  [constants.store_path_enum.owner_id] = "owner_id",
  [constants.store_path_enum.level] = "level",
  [constants.store_path_enum.turn] = "turn",
  [constants.store_path_enum.action_anim_seq] = "action_anim_seq",
  [constants.store_path_enum.action_anim] = "action_anim",
  [constants.store_path_enum.current_player_index] = "current_player_index",
  [constants.store_path_enum.pending_choice] = "pending_choice",
}

return constants
