return {
  "suites.domain.chance",
  "suites.domain.land",
  "suites.domain.item",
  "suites.domain.movement",
  "suites.domain.landing",
  "suites.domain.market",
  "suites.domain.paid_currency",
  "suites.domain.config_sanity",
  "suites.runtime.startup_release",

  "suites.gameplay.gameplay_core",
  "suites.gameplay.gameplay_runtime",
  "suites.gameplay.gameplay_coroutine",
  "suites.gameplay.gameplay_loop",
  "suites.gameplay.gameplay_afk",
  "suites.runtime.runtime_bootstrap",

  "suites.presentation.presentation_ui_timing_anim",
  "suites.presentation.presentation_ui_model_dispatch",
  "suites.presentation.presentation_ui_interaction",
  "suites.presentation.presentation_ui_popup_market",
  "suites.presentation.presentation_ui_action_status",
  "suites.presentation.presentation_ui_action_anim",
  "suites.presentation.presentation_ui_event_handlers",
  "suites.presentation.presentation_ui_event_bindings",
  "suites.presentation.presentation_player_colors",
  "suites.presentation.read_model_contract",
  "suites.architecture.architecture_guard_contract",
  "suites.architecture.arch_view_contract",
  "suites.architecture.guard_scripts_contract",
  "suites.architecture.usecase_boundary_contract",
  "suites.architecture.cross_module_contract",
  "suites.presentation.ui_gate_contract",
  "suites.runtime.runtime_ports_contract",
  "suites.presentation.ui_runtime_state_contract",

  "suites.runtime.test_profiles",
  "suites.runtime.misc",
}
