-- Generated by tools/quality/crap_gate.lua --update-baseline.
-- Per-file accepted CRAP-violation counts (ratchet baseline). Do not hand-edit;
-- regenerate after legitimate complexity changes. A violation is a function
-- whose crap >= max(crap_threshold, complexity + 1).
return {
  base_threshold = 7,
  files = {
  },
}
