-- Generated by tools/quality/crap_gate.lua --update-baseline.
-- Per-file accepted CRAP-violation counts (ratchet baseline). Do not hand-edit;
-- regenerate after legitimate complexity changes. A violation is a function
-- whose crap >= max(crap_threshold, complexity + 1).
return {
  base_threshold = 7,
  files = {
    ["src/app/profile_bootstrap.lua"] = 1,
    ["src/rules/choice_handlers/item.lua"] = 1,
    ["src/rules/items/phase.lua"] = 1,
    ["src/rules/land/effect_chance.lua"] = 1,
    ["src/ui/coord/event_log_view.lua"] = 1,
    ["src/ui/coord/popup.lua"] = 1,
    ["src/ui/input/canvas_route/item_slots.lua"] = 1,
    ["src/ui/input/dispatch/game_action.lua"] = 1,
    ["src/ui/ports/callbacks.lua"] = 1,
    ["src/ui/render/anim/overlay_compute.lua"] = 1,
    ["src/ui/render/anim/overlay_runtime.lua"] = 1,
    ["src/ui/render/anim/unit_overlay.lua"] = 2,
    ["src/ui/render/board/placement.lua"] = 2,
    ["src/ui/render/board_feedback/catalog.lua"] = 1,
    ["src/ui/render/move_anim/playback.lua"] = 1,
    ["src/ui/render/widgets/player_slots.lua"] = 1,
    ["src/ui/state/canvas_store.lua"] = 1,
    ["src/ui/view/choice_support.lua"] = 1,
    ["src/ui/view/role_avatar.lua"] = 1,
  },
}
