-- Pure logic for the complexity-aware CRAP ratchet gate.
-- IO (reading collect JSON, building the report, writing the baseline file,
-- process exit) lives in tools/quality/crap_gate.lua; this module is
-- side-effect free so it can be unit tested directly.
local gate = {}

-- A function's CRAP floor at 100% coverage equals its cyclomatic complexity,
-- so a flat <base bar can never be met by cx>=base functions. The ceiling is
-- complexity-aware: max(base_threshold, cx + 1).
--   cx <= base_threshold-1 → ceiling = base_threshold (legacy bar, push coverage)
--   cx >= base_threshold   → ceiling = cx + 1 (accept the irreducible floor,
--                            but still flag a full-point coverage gap above it)
function gate.ceiling(complexity, base_threshold)
  local floor_plus = (complexity or 0) + 1
  if floor_plus > base_threshold then return floor_plus end
  return base_threshold
end

function gate.is_violation(fn, base_threshold)
  return (fn.crap or 0) >= gate.ceiling(fn.complexity or 0, base_threshold)
end

-- Group violating functions by source_path. Returns a map
-- source_path -> { count = N, functions = { {name, complexity, crap, ...}, ... } }.
function gate.violations_by_file(functions, base_threshold)
  local by_file = {}
  for _, fn in ipairs(functions or {}) do
    if gate.is_violation(fn, base_threshold) then
      local bucket = by_file[fn.source_path]
      if not bucket then
        bucket = { count = 0, functions = {} }
        by_file[fn.source_path] = bucket
      end
      bucket.count = bucket.count + 1
      bucket.functions[#bucket.functions + 1] = {
        name = fn.name,
        complexity = fn.complexity,
        crap = fn.crap,
        coverage = fn.coverage,
        start_line = fn.start_line,
      }
    end
  end
  return by_file
end

function gate.total_violations(by_file)
  local total = 0
  for _, bucket in pairs(by_file or {}) do
    total = total + bucket.count
  end
  return total
end

-- Compare current violations to a baseline. Returns a sorted list of
-- regressions: files whose current violation count exceeds the baseline.
function gate.evaluate(by_file, baseline)
  local allowed = (baseline and baseline.files) or {}
  local regressions = {}
  for source_path, bucket in pairs(by_file or {}) do
    local budget = allowed[source_path] or 0
    if bucket.count > budget then
      local fns = {}
      for _, fn in ipairs(bucket.functions) do fns[#fns + 1] = fn end
      table.sort(fns, function(a, b) return (a.crap or 0) > (b.crap or 0) end)
      regressions[#regressions + 1] = {
        source_path = source_path,
        count = bucket.count,
        allowed = budget,
        functions = fns,
      }
    end
  end
  table.sort(regressions, function(a, b) return a.source_path < b.source_path end)
  return regressions
end

-- Render a baseline Lua module source string from current violation counts.
function gate.render_baseline(base_threshold, by_file)
  local files = {}
  for source_path in pairs(by_file or {}) do files[#files + 1] = source_path end
  table.sort(files)
  local lines = {
    "-- Generated by tools/quality/crap_gate.lua --update-baseline.",
    "-- Per-file accepted CRAP-violation counts (ratchet baseline). Do not hand-edit;",
    "-- regenerate after legitimate complexity changes. A violation is a function",
    "-- whose crap >= max(crap_threshold, complexity + 1).",
    "return {",
    string.format("  base_threshold = %d,", base_threshold),
    "  files = {",
  }
  for _, source_path in ipairs(files) do
    lines[#lines + 1] = string.format("    [%q] = %d,", source_path, by_file[source_path].count)
  end
  lines[#lines + 1] = "  },"
  lines[#lines + 1] = "}"
  lines[#lines + 1] = ""
  return table.concat(lines, "\n")
end

return gate
