local ui_runtime = require("src.ui.state.runtime")
local state_runtime = require("src.state.runtime")

local function make_state()
  return state_runtime.ensure_all({})
end

describe("ui.state.runtime (delegation facade)", function()
  it("ensure_all returns a valid state table", function()
    local state = make_state()
    local result = ui_runtime.ensure_all(state)
    assert(type(result) == "table", "expected table")
  end)

  it("ensure_ui_runtime returns state", function()
    local state = make_state()
    local result = ui_runtime.ensure_ui_runtime(state)
    assert(type(result) == "table", "expected table")
  end)

  it("ensure_board_runtime returns state", function()
    local state = make_state()
    local result = ui_runtime.ensure_board_runtime(state)
    assert(type(result) == "table", "expected table")
  end)

  it("ensure_anim_runtime returns state", function()
    local state = make_state()
    local result = ui_runtime.ensure_anim_runtime(state)
    assert(type(result) == "table", "expected table")
  end)

  it("ensure_turn_runtime returns state", function()
    local state = make_state()
    local result = ui_runtime.ensure_turn_runtime(state)
    assert(type(result) == "table", "expected table")
  end)

  it("ensure_debug_runtime returns state", function()
    local state = make_state()
    local result = ui_runtime.ensure_debug_runtime(state)
    assert(type(result) == "table", "expected table")
  end)

  it("is_ui_dirty returns boolean", function()
    local state = make_state()
    local result = ui_runtime.is_ui_dirty(state)
    assert(result == true or result == false or result == nil, "expected boolean or nil")
  end)

  it("set_ui_dirty and is_ui_dirty round-trip", function()
    local state = make_state()
    ui_runtime.set_ui_dirty(state, true)
    local dirty = ui_runtime.is_ui_dirty(state)
    assert(dirty == true, "expected dirty after set")
  end)

  it("get_ui_model returns nil or table on fresh state", function()
    local state = make_state()
    local model = ui_runtime.get_ui_model(state)
    assert(model == nil or type(model) == "table", "expected nil or table")
  end)

  it("set_ui_model stores and get_ui_model retrieves it", function()
    local state = make_state()
    local mock_model = { version = 1 }
    ui_runtime.set_ui_model(state, mock_model)
    local retrieved = ui_runtime.get_ui_model(state)
    assert(retrieved == mock_model, "expected model round-trip")
  end)

  it("set_local_actor_role_id sets state.local_actor_role_id", function()
    local state = make_state()
    ui_runtime.set_local_actor_role_id(state, 99)
    assert(state.local_actor_role_id == 99, "expected role_id stored in state")
  end)

  it("get_local_actor_role_id returns the set value", function()
    local state = make_state()
    ui_runtime.set_local_actor_role_id(state, 42)
    local result = ui_runtime.get_local_actor_role_id(state)
    assert(result == 42 or state.local_actor_role_id == 42, "expected role_id accessible")
  end)

  it("get_pending_choice returns nil on fresh state", function()
    local state = make_state()
    local result = ui_runtime.get_pending_choice(state)
    assert(result == nil, "expected nil pending choice on fresh state")
  end)

  it("get_pending_choice_id returns nil on fresh state", function()
    local state = make_state()
    local result = ui_runtime.get_pending_choice_id(state)
    assert(result == nil, "expected nil choice_id")
  end)

  it("set_pending_choice_id stores and get retrieves it", function()
    local state = make_state()
    ui_runtime.set_pending_choice_id(state, "choice_123")
    local result = ui_runtime.get_pending_choice_id(state)
    assert(result == "choice_123", "expected choice_id round-trip")
  end)

  it("get_pending_choice_elapsed returns nil or number", function()
    local state = make_state()
    local result = ui_runtime.get_pending_choice_elapsed(state)
    assert(result == nil or type(result) == "number", "expected nil or number")
  end)

  it("set_pending_choice_elapsed stores elapsed", function()
    local state = make_state()
    ui_runtime.set_pending_choice_elapsed(state, 3.5)
    local result = ui_runtime.get_pending_choice_elapsed(state)
    assert(result == 3.5 or result ~= nil, "expected elapsed stored")
  end)

  it("get_modal_elapsed returns nil on fresh state", function()
    local state = make_state()
    local result = ui_runtime.get_modal_elapsed(state)
    assert(result == nil or type(result) == "number", "expected nil or number")
  end)

  it("get_modal_ref returns nil on fresh state", function()
    local state = make_state()
    local result = ui_runtime.get_modal_ref(state)
    assert(result == nil or type(result) == "table", "expected nil or table")
  end)

  it("log_once skips duplicate keys", function()
    local state = make_state()
    local first = ui_runtime.log_once(state, "info", "k1", "message")
    local second = ui_runtime.log_once(state, "info", "k1", "message2")
    assert(first == true, "expected first log_once to return true")
    assert(second == false, "expected second log_once to return false")
  end)

  it("set_follow_target_position and get round-trip", function()
    local state = make_state()
    local pos = { x = 1, y = 2, z = 3 }
    ui_runtime.set_follow_target_position(state, "player_1", pos)
    local result = ui_runtime.get_follow_target_position(state, "player_1")
    assert(result ~= nil, "expected stored position")
  end)
end)
