local chance_cards = {
  { id = 3001, description = "你出售股票，获利10000金币。", weight = 300, negative = false, target = "self", effect = "add_cash", amount = 10000 },
  { id = 3002, description = "你抽到二等奖，获得奖金1000金币。", weight = 400, negative = false, target = "self", effect = "add_cash", amount = 1000 },
  { id = 3003, description = "你典卖家当，获利2000金币。", weight = 400, negative = false, target = "self", effect = "add_cash", amount = 2000 },
  { id = 3004, description = "你见义勇为，获得奖金5000金币。", weight = 400, negative = false, target = "self", effect = "add_cash", amount = 5000 },
  { id = 3005, description = "你投资失败，损失10000金币。", weight = 400, negative = true, target = "self", effect = "pay_cash", amount = 10000 },
  { id = 3006, description = "你去游乐场，支付1000金币。", weight = 400, negative = true, target = "self", effect = "pay_cash", amount = 1000 },
  { id = 3007, description = "你捐助失学儿童，捐出2000金币。", weight = 400, negative = true, target = "self", effect = "pay_cash", amount = 2000 },
  { id = 3008, description = "你扶老人去医院，垫付5000金币。", weight = 400, negative = true, target = "self", effect = "pay_cash", amount = 5000 },
  { id = 3009, description = "口罩封城，每人领取3000金币救济金。", weight = 400, negative = false, target = "all", effect = "add_cash", amount = 3000 },
  { id = 3010, description = "洪水无情人有情，每人向灾区捐献3000金币。", weight = 400, negative = true, target = "all", effect = "pay_cash", amount = 3000 },
  { id = 3011, description = "股灾降临，每人损失20%金币。", weight = 400, negative = true, target = "all", effect = "percent_pay_cash", percent = 20 },
  { id = 3012, description = "破财消灾，你给每个其他玩家3000金币。", weight = 300, negative = true, target = "self", effect = "pay_others", amount = 3000 },
  { id = 3013, description = "今天是你的生日，每个其他玩家给你3000金币。", weight = 300, negative = false, target = "self", effect = "collect_from_others", amount = 3000 },
  { id = 3014, description = "爸爸爱你，送给你一副滑板", weight = 200, negative = false, target = "self", effect = "set_vehicle", vehicle_id = 4001 },
  { id = 3015, description = "爷爷爱你，送给你一辆三轮车", weight = 200, negative = false, target = "self", effect = "set_vehicle", vehicle_id = 4002 },
  { id = 3016, description = "奶奶爱你，送给你一辆电动车", weight = 200, negative = false, target = "self", effect = "set_vehicle", vehicle_id = 4003 },
  { id = 3017, description = "台风过境，摧毁本回合你经过地块上的所有建筑", weight = 200, negative = false, target = "path", effect = "destroy_buildings_on_path" },
  { id = 3018, description = "强制征地，本回合你经过的所有地块恢复初始状态", weight = 200, negative = false, target = "path", effect = "reset_tiles_on_path" },
  { id = 3019, description = "前方有蛇出没，你后跳一格", weight = 300, negative = false, target = "self", effect = "move_backward", steps = 1 },
  { id = 3020, description = "前方有熊出没，你后退两格", weight = 300, negative = false, target = "self", effect = "move_backward", steps = 2 },
  { id = 3021, description = "前方有债主出没，你后逃三格", weight = 300, negative = false, target = "self", effect = "move_backward", steps = 3 },
  { id = 3022, description = "后方有鞭炮炸响，你前跳一格", weight = 300, negative = false, target = "self", effect = "move_forward", steps = 1 },
  { id = 3023, description = "后方有犬吠，你向前跑两格", weight = 300, negative = false, target = "self", effect = "move_forward", steps = 2 },
  { id = 3024, description = "后方有坠机，你向前狂奔三格", weight = 300, negative = false, target = "self", effect = "move_forward", steps = 3 },
  { id = 3025, description = "财神显灵，你获得一张财神卡。", weight = 200, negative = false, target = "self", effect = "grant_item", item_id = 2017 },
  { id = 3026, description = "穷神显灵，你获得一张穷神卡。", weight = 200, negative = false, target = "self", effect = "grant_item", item_id = 2018 },
  { id = 3027, description = "天使显灵，你获得一张天使卡。", weight = 200, negative = false, target = "self", effect = "grant_item", item_id = 2019 },
  { id = 3028, description = "小偷光临，你随机丢失1张道具卡", weight = 200, negative = true, target = "self", effect = "discard_items", count = 1 },
  { id = 3029, description = "强盗来袭，你丢失所有道具卡", weight = 200, negative = true, target = "self", effect = "discard_items", count = 0 },
  { id = 3030, description = "你遭遇火灾，随机丢失1张地块持有证", weight = 200, negative = true, target = "self", effect = "discard_properties", count = 1 },
  { id = 3031, description = "你突然晕倒了，被送入医院。", weight = 200, negative = true, target = "self", effect = "forced_move", destination_tile_id = 38 },
  { id = 3032, description = "你迷路走进了深山。", weight = 200, negative = true, target = "self", effect = "forced_move", destination_tile_id = 37 },
  { id = 3033, description = "你收到税务通知，立刻赶往税务局交代问题。", weight = 200, negative = true, target = "self", effect = "forced_move", destination_tile_id = 36 },
  { id = 3034, description = "你发现密道，到达黑市。", weight = 200, negative = false, target = "self", effect = "forced_move", destination_tile_id = 39 },
  { id = 3035, description = "妈妈爱你，送给你一辆路虎", weight = 100, negative = false, target = "self", effect = "set_vehicle", vehicle_id = 4004 },
  { id = 3036, description = "姐姐爱你，送给你一辆哈雷摩托", weight = 100, negative = false, target = "self", effect = "set_vehicle", vehicle_id = 4005 },
  { id = 3037, description = "干爹爱你，送给你一辆法拉利", weight = 100, negative = false, target = "self", effect = "set_vehicle", vehicle_id = 4006 },
}

return chance_cards