local items = {
  {
    id = 2001,
    name = "免费卡",
    tier = 1,
    shop_currency = "广告",
    shop_price = 1,
    weight = 1000,
    angel_immune = false,
    timing = "rent_prompt",
    usage = "确认使用，免除本次租金",
    description = "停留在其他玩家地块时，可使用免费卡免交本次租金。",
  },
  {
    id = 2002,
    name = "遥控骰子卡",
    tier = 1,
    shop_currency = "金币",
    shop_price = 1000,
    weight = 1000,
    angel_immune = false,
    timing = "pre_action",
    usage = "主动使用，设定骰子点数",
    description = "投骰子前可设置骰子点数，点击循环 1~6 后确定。",
  },
  {
    id = 2003,
    name = "骰子加倍卡",
    tier = 1,
    shop_currency = "金币",
    shop_price = 1000,
    weight = 1000,
    angel_immune = false,
    timing = "pre_move",
    usage = "投出后触发，令本次点数加倍",
    description = "投出骰子后可使用，将本次投掷步数翻倍。",
  },
  {
    id = 2004,
    name = "路障卡",
    tier = 1,
    shop_currency = "金币",
    shop_price = 1000,
    weight = 1000,
    angel_immune = true,
    timing = "manual",
    usage = "主动使用，前后 3 格放置路障",
    description = "释放后可在前后 3 格放置路障，经过者停留并清除路障。",
  },
  {
    id = 2005,
    name = "地雷卡",
    tier = 1,
    shop_currency = "金币",
    shop_price = 1000,
    weight = 1000,
    angel_immune = true,
    timing = "manual",
    usage = "主动使用，在脚下放置地雷",
    description = "在当前位置放置地雷，经过者触发炸毁座驾并送医。",
  },
  {
    id = 2006,
    name = "清障卡",
    tier = 1,
    shop_currency = "金币",
    shop_price = 1000,
    weight = 1000,
    angel_immune = false,
    timing = "pre_action",
    usage = "主动使用，清除前方 12 格障碍",
    description = "行动前释放机器人清除前方 12 格（含分叉）路障/地雷。",
  },
  {
    id = 2007,
    name = "偷窃卡",
    tier = 2,
    shop_currency = "乐园币",
    shop_price = 10,
    weight = 500,
    angel_immune = true,
    timing = "pass_player",
    usage = "经过玩家时触发，选择一个道具偷取",
    description = "路过其他玩家弹窗选择是否使用，指定道具转移到自己背包。",
  },
  {
    id = 2008,
    name = "怪兽卡",
    tier = 2,
    shop_currency = "乐园币",
    shop_price = 10,
    weight = 500,
    angel_immune = false,
    timing = "manual",
    usage = "主动使用，拆除前后 3 格建筑",
    description = "选择前后 3 格内的建筑释放怪兽拆除该建筑。",
  },
  {
    id = 2009,
    name = "强征卡",
    tier = 2,
    shop_currency = "乐园币",
    shop_price = 10,
    weight = 500,
    angel_immune = false,
    timing = "rent_prompt",
    usage = "停留他人地块时触发，支付总价强制买下",
    description = "停留在他人地块时支付地块+建筑总价并转移所有权。",
  },
  {
    id = 2010,
    name = "免税卡",
    tier = 2,
    shop_currency = "乐园币",
    shop_price = 10,
    weight = 500,
    angel_immune = false,
    timing = "tax_prompt",
    usage = "征税时触发，抵扣本次税金",
    description = "到税务局或被查税时可出示免税卡免除本次税费。",
  },
  {
    id = 2011,
    name = "均富卡",
    tier = 2,
    shop_currency = "乐园币",
    shop_price = 10,
    weight = 500,
    angel_immune = true,
    timing = "manual",
    usage = "主动使用，选择一名玩家平分双方资金",
    description = "选择一名玩家，将双方现金总和平分。",
  },
  {
    id = 2012,
    name = "流放卡",
    tier = 2,
    shop_currency = "乐园币",
    shop_price = 10,
    weight = 500,
    angel_immune = true,
    timing = "manual",
    usage = "主动使用，选择一名玩家送往深山",
    description = "强制目标玩家移动到深山并开始停留回合。",
  },
  {
    id = 2013,
    name = "导弹卡",
    tier = 3,
    shop_currency = "金豆",
    shop_price = 5,
    weight = 250,
    angel_immune = false,
    timing = "manual",
    usage = "主动使用，前后 3 格范围导弹轰炸",
    description = "前后 3 格选一格，摧毁建筑与座驾，所有玩家送医。",
  },
  {
    id = 2014,
    name = "查税卡",
    tier = 3,
    shop_currency = "金豆",
    shop_price = 5,
    weight = 250,
    angel_immune = true,
    timing = "manual",
    usage = "主动使用，目标支付 50% 现金的所得税",
    description = "选择一名玩家立刻支付 50% 现金，可被免税卡抵消，天使免疫。",
  },
  {
    id = 2015,
    name = "请神卡",
    tier = 3,
    shop_currency = "金豆",
    shop_price = 5,
    weight = 250,
    angel_immune = false,
    timing = "manual",
    usage = "主动使用，夺取目标的附身神",
    description = "选择一名玩家，将其附身神转移到自己身上（仅保留一位神）。",
  },
  {
    id = 2016,
    name = "送神卡",
    tier = 3,
    shop_currency = "金豆",
    shop_price = 5,
    weight = 250,
    angel_immune = false,
    timing = "trigger_poor_god",
    usage = "被穷神附身时触发，将穷神送给他人",
    description = "自己有穷神时可选择一名玩家转移穷神（目标仅保留一位神）。",
  },
  {
    id = 2017,
    name = "财神卡",
    tier = 3,
    shop_currency = "金豆",
    shop_price = 5,
    weight = 0,
    angel_immune = false,
    timing = "manual",
    usage = "主动使用，财神附身 5 回合收款翻倍",
    description = "财神附身，持续 5 回合，租金/奖金翻倍。",
  },
  {
    id = 2018,
    name = "穷神卡",
    tier = 3,
    shop_currency = "金豆",
    shop_price = 5,
    weight = 0,
    angel_immune = false,
    timing = "manual",
    usage = "主动使用，给目标附身穷神 5 回合付款翻倍",
    description = "选择玩家让其穷神附身 5 回合，租金/罚金翻倍。",
  },
  {
    id = 2019,
    name = "天使卡",
    tier = 3,
    shop_currency = "金豆",
    shop_price = 5,
    weight = 0,
    angel_immune = false,
    timing = "manual",
    usage = "主动使用，天使附身 5 回合免疫负面",
    description = "天使附身 5 回合，免疫负面卡牌/地雷/路障/送医/深山。",
  },
}

return items
