local tiles = {
  { id = 1, name = "福州路", type = "land", price = 100, base_rent = 50, row = 9, col = 8 },
  { id = 2, name = "台北路", type = "land", price = 150, base_rent = 75, row = 9, col = 7 },
  { id = 3, name = "海口路", type = "land", price = 200, base_rent = 100, row = 9, col = 6 },
  { id = 4, name = "广州路", type = "land", price = 250, base_rent = 125, row = 9, col = 4 },
  { id = 5, name = "香港路", type = "land", price = 300, base_rent = 150, row = 9, col = 3 },
  { id = 6, name = "澳门路", type = "land", price = 350, base_rent = 175, row = 9, col = 2 },
  { id = 7, name = "南宁路", type = "land", price = 400, base_rent = 200, row = 8, col = 1 },
  { id = 8, name = "贵阳路", type = "land", price = 450, base_rent = 225, row = 7, col = 1 },
  { id = 9, name = "昆明路", type = "land", price = 500, base_rent = 250, row = 6, col = 1 },
  { id = 10, name = "成都路", type = "land", price = 550, base_rent = 275, row = 4, col = 1 },
  { id = 11, name = "西宁路", type = "land", price = 600, base_rent = 300, row = 3, col = 1 },
  { id = 12, name = "拉萨路", type = "land", price = 650, base_rent = 325, row = 2, col = 1 },
  { id = 13, name = "乌鲁木齐路", type = "land", price = 700, base_rent = 350, row = 1, col = 2 },
  { id = 14, name = "兰州路", type = "land", price = 750, base_rent = 375, row = 1, col = 3 },
  { id = 15, name = "呼和浩特路", type = "land", price = 800, base_rent = 400, row = 1, col = 4 },
  { id = 16, name = "哈尔滨路", type = "land", price = 850, base_rent = 425, row = 1, col = 6 },
  { id = 17, name = "长春路", type = "land", price = 900, base_rent = 450, row = 1, col = 7 },
  { id = 18, name = "沈阳路", type = "land", price = 950, base_rent = 475, row = 1, col = 8 },
  { id = 19, name = "石家庄路", type = "land", price = 1000, base_rent = 500, row = 2, col = 9 },
  { id = 20, name = "郑州路", type = "land", price = 1050, base_rent = 525, row = 3, col = 9 },
  { id = 21, name = "合肥路", type = "land", price = 1100, base_rent = 550, row = 4, col = 9 },
  { id = 22, name = "济南路", type = "land", price = 1150, base_rent = 575, row = 6, col = 9 },
  { id = 23, name = "南京路", type = "land", price = 1200, base_rent = 600, row = 7, col = 9 },
  { id = 24, name = "杭州路", type = "land", price = 1250, base_rent = 625, row = 8, col = 9 },
  { id = 25, name = "南昌路", type = "land", price = 250, base_rent = 125, row = 5, col = 2 },
  { id = 26, name = "长沙路", type = "land", price = 350, base_rent = 175, row = 5, col = 3 },
  { id = 27, name = "武汉路", type = "land", price = 450, base_rent = 225, row = 5, col = 4 },
  { id = 28, name = "太原路", type = "land", price = 550, base_rent = 275, row = 4, col = 5 },
  { id = 29, name = "西安路", type = "land", price = 650, base_rent = 325, row = 3, col = 5 },
  { id = 30, name = "银川路", type = "land", price = 750, base_rent = 375, row = 2, col = 5 },
  { id = 31, name = "重庆路", type = "land", price = 1500, base_rent = 750, row = 7, col = 5 },
  { id = 32, name = "天津路", type = "land", price = 2000, base_rent = 1000, row = 6, col = 5 },
  { id = 33, name = "北京路", type = "land", price = 2500, base_rent = 1250, row = 5, col = 7 },
  { id = 34, name = "上海路", type = "land", price = 3000, base_rent = 1500, row = 5, col = 8 },
  { id = 35, name = "起点", type = "start", row = 9, col = 9 },
  { id = 36, name = "医院", type = "hospital", row = 9, col = 1 },
  { id = 37, name = "深山", type = "mountain", row = 1, col = 1 },
  { id = 38, name = "税务局", type = "tax", row = 1, col = 9 },
  { id = 39, name = "黑市", type = "market", row = 5, col = 5 },
  { id = 40, name = "机会卡", type = "chance", row = 5, col = 1 },
  { id = 41, name = "机会卡", type = "chance", row = 5, col = 6 },
  { id = 42, name = "机会卡", type = "chance", row = 8, col = 5 },
  { id = 43, name = "机会卡", type = "chance", row = 5, col = 9 },
  { id = 44, name = "道具卡", type = "item", row = 1, col = 5 },
  { id = 45, name = "道具卡", type = "item", row = 9, col = 5 },
}

return tiles
