local tiles = {
  { id = 1, name = "福州路", type = "land", price = 100, base_rent = 50 },
  { id = 2, name = "台北路", type = "land", price = 150, base_rent = 75 },
  { id = 3, name = "海口路", type = "land", price = 200, base_rent = 100 },
  { id = 4, name = "广州路", type = "land", price = 250, base_rent = 125 },
  { id = 5, name = "香港路", type = "land", price = 300, base_rent = 150 },
  { id = 6, name = "澳门路", type = "land", price = 350, base_rent = 175 },
  { id = 7, name = "南宁路", type = "land", price = 400, base_rent = 200 },
  { id = 8, name = "贵阳路", type = "land", price = 450, base_rent = 225 },
  { id = 9, name = "昆明路", type = "land", price = 500, base_rent = 250 },
  { id = 10, name = "成都路", type = "land", price = 550, base_rent = 275 },
  { id = 11, name = "西宁路", type = "land", price = 600, base_rent = 300 },
  { id = 12, name = "拉萨路", type = "land", price = 650, base_rent = 325 },
  { id = 13, name = "乌鲁木齐路", type = "land", price = 700, base_rent = 350 },
  { id = 14, name = "兰州路", type = "land", price = 750, base_rent = 375 },
  { id = 15, name = "呼和浩特路", type = "land", price = 800, base_rent = 400 },
  { id = 16, name = "哈尔滨路", type = "land", price = 850, base_rent = 425 },
  { id = 17, name = "长春路", type = "land", price = 900, base_rent = 450 },
  { id = 18, name = "沈阳路", type = "land", price = 950, base_rent = 475 },
  { id = 19, name = "石家庄路", type = "land", price = 1000, base_rent = 500 },
  { id = 20, name = "郑州路", type = "land", price = 1050, base_rent = 525 },
  { id = 21, name = "合肥路", type = "land", price = 1100, base_rent = 550 },
  { id = 22, name = "济南路", type = "land", price = 1150, base_rent = 575 },
  { id = 23, name = "南京路", type = "land", price = 1200, base_rent = 600 },
  { id = 24, name = "杭州路", type = "land", price = 1250, base_rent = 625 },
  { id = 25, name = "南昌路", type = "land", price = 250, base_rent = 125 },
  { id = 26, name = "长沙路", type = "land", price = 350, base_rent = 175 },
  { id = 27, name = "武汉路", type = "land", price = 450, base_rent = 225 },
  { id = 28, name = "太原路", type = "land", price = 550, base_rent = 275 },
  { id = 29, name = "西安路", type = "land", price = 650, base_rent = 325 },
  { id = 30, name = "银川路", type = "land", price = 750, base_rent = 375 },
  { id = 31, name = "重庆路", type = "land", price = 1500, base_rent = 750 },
  { id = 32, name = "天津路", type = "land", price = 2000, base_rent = 1000 },
  { id = 33, name = "北京路", type = "land", price = 2500, base_rent = 1250 },
  { id = 34, name = "上海路", type = "land", price = 3000, base_rent = 1500 },
  { id = 35, name = "起点", type = "start" },
  { id = 36, name = "医院", type = "hospital" },
  { id = 37, name = "深山", type = "mountain" },
  { id = 38, name = "税务局", type = "tax" },
  { id = 39, name = "黑市", type = "market" },
  { id = 40, name = "机会卡", type = "chance" },
  { id = 41, name = "机会卡", type = "chance" },
  { id = 42, name = "机会卡", type = "chance" },
  { id = 43, name = "机会卡", type = "chance" },
  { id = 44, name = "道具卡", type = "item" },
  { id = 45, name = "道具卡", type = "item" },
}

return tiles
