---@type table<ItemCode, ItemConfig>
local ItemConfig = {
    ["flash_light"] = {
        id = 1073946637,
        icon = 1805944598,
        name = "手电筒",
        desc = "照亮前方的路，获得更清晰的视野。",
        quality = 1,
        durability = 100,
        tag = "特殊道具",
        value = 2500,
        abilities = {
            [1] = "flashlight_switch_on"
        }
    },
    ["machete"] = {
        id = 1073971261,
        icon = 1776123006,
        name = "弯刀",
        desc = "一把锋利的弯刀，适合近距离战斗#cff0000（未实装）",
        quality = 3,
        value = 5000,
        tag = "特殊道具",
    },
    ["fish_spear"] = {
        id = 1073967225,
        icon = 1729502487,
        name = "鱼叉",
        desc = "远程攻击目标，被攻击的目标会短暂眩晕 #cff8800水鬼利器#l #cff0000（未实装）",
        quality = 3,
        value = 5000,
        tag = "特殊道具",
    },
    ["shotgun"] = {
        id = 1074016361,
        name = "猎枪",
        desc = "对实体怪物造成高额伤害 #cff8800猎人利器#l",
        quality = 3,
        value = 5000,
        tag = "特殊道具",
    },
    ["medical_box"] = {
        id = 1073963015,
        icon = 1854643932,
        name = "医疗箱",
        desc = "治疗自己或队友，回复一定的生命值 #cff8800医生利器#l #cff0000（未实装）",
        quality = 5,
        durability = 50,
        value = 5000,
        tag = "特殊道具",
    },
    ["camera"] = {
        id = 1073959015,
        icon = 1808881201,
        name = "相机",
        desc = "短暂致盲怪物，仅对靠视觉的怪物有效 #cff8800报童利器#l #cff0000（未实装）",
        quality = 3,
        value = 5000,
        tag = "特殊道具",
    },
    ["shovel"] = {
        id = 1074012204,
        icon = 1611884712,
        name = "铲子",
        desc = "探索工具，可破坏部分地形。 #cff8800矿工利器#l",
        quality = 3,
        value = 5000,
        tag = "特殊道具",
    },
    ["bomb"] = {
        id = 1073954917,
        icon = 1663012506,
        name = "炸弹",
        desc = "爆炸伤害，对群体怪物造成伤害，对正中怪物造成半命伤害 #cff8800爆破师利器#l #cff0000（未实装）",
        quality = 5,
        value = 5000,
        tag = "特殊道具",
    },
    ["scorpion_badge"] = {
        id = 0,
        name = "徽章-毒蝎",
        desc = "当被怪物控制时，可快速解控并眩晕怪物#cff0000（未实装）",
        quality = 1,
        durability = 3,
        value = 500,
        tag = "特殊道具",
    },
    ["cocoon_badge"] = {
        id = 0,
        name = "徽章-破茧",
        desc = "倒地后可快速复活并恢复一定生命值#cff0000（未实装）",
        quality = 1,
        durability = 1,
        value = 500,
        tag = "特殊道具",
    },
    ["hawkeye_badge"] = {
        id = 0,
        name = "徽章-鹰眼",
        desc = "透视附近高危怪物位置#cff0000（未实装）",
        quality = 1,
        durability = 3,
        value = 500,
        tag = "特殊道具",
    },
    ["steel_gloves"] = {
        id = 0,
        name = "钢铁拳套",
        desc = "形成护盾抵挡一次攻击 #cff8800黑拳利器#l #cff0000（未实装）",
        quality = 3,
        value = 5000,
        tag = "特殊道具",
    },
    ["mask"] = {
        id = 1073950847,
        name = "面具",
        desc = "古老的九州，曾有一个文明",
        quality = 10,
        value = 500,
        tag = "回收物",
    },
    ["bronze_coin"] = {
        id = 1073922073,
        name = "铜币",
        desc = "古钱，它们在古代很流通",
        quality = 5,
        value = 850,
        tag = "回收物",
    },
    ["golden_sculpture"] = {
        id = 1073848334,
        name = "金雕",
        desc = "胜利的象征，是一种荣誉",
        quality = 15,
        value = 3500,
        tag = "回收物",
    },
    ["bronze_sculpture"] = {
        id = 1073872945,
        name = "铜雕",
        desc = "沙漠，无边无际",
        quality = 15,
        value = 1500,
        tag = "回收物",
    },
    ["teddy_bear"] = {
        id = 1073909777,
        name = "玩具熊",
        desc = "圣诞礼物，送给你",
        quality = 2,
        value = 200,
        tag = "回收物",
    },
    ["bronze_tripod"] = {
        id = 1073905684,
        name = "青铜鼎",
        desc = "重器，重器，小心搬运",
        quality = 35,
        value = 2200,
        tag = "回收物",
    },
    ["gold_watch"] = {
        id = 1073897510,
        name = "金表",
        desc = "时间的守护者，时刻提醒你前进的方向",
        quality = 3,
        value = 2800,
        tag = "回收物",
    },
    ["mysterious_jar"] = {
        id = 1073930281,
        name = "秘罐",
        desc = "绷带裹着罐子",
        quality = 15,
        tag = "回收物",
    },
    ["embroidered_tension"] = {
        id = 1073856552,
        name = "绣绷",
        desc = "古织技术，一件艺术品",
        quality = 3,
        value = 300,
        tag = "回收物",
    },
    ["bronze_cup"] = {
        id = 1073975412,
        name = "铜杯",
        desc = "一杯水，一杯血",
        quality = 15,
        value = 850,
        tag = "回收物",
    },
    ["stone_sculpture"] = {
        id = 1073889330,
        name = "石雕",
        desc = "一笔一划，一划一刻",
        quality = 25,
        value = 800,
        tag = "回收物",
    },
    ["deathstation_clock"] = {
        id = 1073881104,
        name = "绝命时钟",
        desc = "绝命火车站，时间定格了",
        quality = 15,
        tag = "回收物",
    }
}

return ItemConfig