return {
  source_roots = { "src" },
  component_rules = {
    { name = "entry", match = { "^src%.entry$", "^src%.entry%..+" }, component = "entry" },
    { name = "host", match = { "^src%.host$", "^src%.host%..+" }, component = "host" },
    { name = "ui", match = { "^src%.ui$", "^src%.ui%..+" }, component = "ui" },
    { name = "turn", match = { "^src%.turn$", "^src%.turn%..+" }, component = "turn" },
    { name = "player", match = { "^src%.player$", "^src%.player%..+" }, component = "player" },
    { name = "computer", match = { "^src%.computer$", "^src%.computer%..+" }, component = "computer" },
    { name = "rules", match = { "^src%.rules$", "^src%.rules%..+" }, component = "rules" },
    { name = "state_access", match = { "^src%.state%.state_access%..+" }, component = "core" },
    { name = "player_state_bridge", match = { "^src%.state%.player_state$" }, component = "game_runtime" },
    { name = "state_root", match = { "^src%.state$", "^src%.state%..+" }, component = "state" },
    { name = "config_root", match = { "^src%.config$", "^src%.config%..+" }, component = "config" },
    { name = "app", match = { "^src%.app$", "^src%.app%..+" }, component = "app" },
    { name = "core", match = { "^src%.core%..+" }, component = "core" },
    { name = "presentation", match = { "^src%.presentation%..+" }, component = "presentation" },
    { name = "game_flow", match = { "^src%.game%.flow%..+" }, component = "game_flow" },
    { name = "game_systems", match = { "^src%.game%.systems%..+", "^src%.game%.ports%..+" }, component = "game_systems" },
    { name = "game_ai", match = { "^src%.game%.ai%..+", "^src%.game%.core%.ai%..+" }, component = "game_ai" },
    { name = "state", match = {
      "^src%.game%.core%.player$",
      "^src%.game%.core%.player%..+",
      "^src%.game%.core%.runtime%.game$",
    }, component = "state" },
    { name = "game_runtime", match = {
      "^src%.game%.scheduler$",
      "^src%.game%.runtime%..+",
      "^src%.game%.scheduler%..+",
      "^src%.game%.core%.runtime%..+",
      "^src%.game%.legacy%..+",
    }, component = "game_runtime" },
    { name = "infrastructure", match = { "^src%.infrastructure%..+" }, component = "infrastructure" },
  },
  abstract_rules = {
    { name = "core_ports", match = { "^src%.core%.ports%..+" } },
    { name = "game_ports", match = { "^src%.game%.ports%..+" } },
    { name = "rules_ports", match = { "^src%.rules%.ports%..+" } },
  },
  forbidden_dependency_rules = {
    {
      name = "ui_no_player",
      description = "ui layer must not depend on player modules directly",
      from = { "^src%.ui%..+" },
      to = { "^src%.player%..+" },
    },
    {
      name = "ui_no_computer",
      description = "ui layer must not depend on computer modules directly",
      from = { "^src%.ui%..+" },
      to = { "^src%.computer%..+" },
    },
    {
      name = "ui_no_rules",
      description = "ui layer must not depend on rules modules directly",
      from = { "^src%.ui%..+" },
      to = { "^src%.rules%..+" },
    },
    {
      name = "turn_no_ui",
      description = "turn layer must not depend on ui modules directly",
      from = { "^src%.turn%..+" },
      to = { "^src%.ui%..+" },
    },
    {
      name = "player_no_turn",
      description = "player layer must not depend on turn modules directly",
      from = { "^src%.player%..+" },
      to = { "^src%.turn%..+" },
    },
    {
      name = "player_no_ui",
      description = "player layer must not depend on ui modules directly",
      from = { "^src%.player%..+" },
      to = { "^src%.ui%..+" },
    },
    {
      name = "player_no_host",
      description = "player layer must not depend on host modules directly",
      from = { "^src%.player%..+" },
      to = { "^src%.host%..+", "^src%.entry%..+" },
    },
    {
      name = "computer_no_turn",
      description = "computer layer must not depend on turn modules directly",
      from = { "^src%.computer%..+" },
      to = { "^src%.turn%..+" },
    },
    {
      name = "computer_no_ui",
      description = "computer layer must not depend on ui modules directly",
      from = { "^src%.computer%..+" },
      to = { "^src%.ui%..+" },
    },
    {
      name = "computer_no_host",
      description = "computer layer must not depend on host modules directly",
      from = { "^src%.computer%..+" },
      to = { "^src%.host%..+", "^src%.entry%..+" },
    },
    {
      name = "rules_no_outer_layers",
      description = "rules layer must stay inner and not depend on turn/ui/player/computer/host/entry",
      from = { "^src%.rules%..+" },
      to = {
        "^src%.turn%..+",
        "^src%.ui%..+",
        "^src%.player%..+",
        "^src%.computer%..+",
        "^src%.host%..+",
        "^src%.entry%..+",
      },
    },
    {
      name = "state_no_outer_layers",
      description = "state layer must stay pure and not depend on gameplay, ui, host, or entry layers",
      from = { "^src%.state%..+" },
      to = {
        "^src%.turn%..+",
        "^src%.ui%..+",
        "^src%.player%..+",
        "^src%.computer%..+",
        "^src%.rules%..+",
        "^src%.host%..+",
        "^src%.entry%..+",
      },
    },
    {
      name = "config_no_outer_layers",
      description = "config layer must not depend on gameplay, ui, host, or entry layers",
      from = { "^src%.config%..+" },
      to = {
        "^src%.turn%..+",
        "^src%.ui%..+",
        "^src%.player%..+",
        "^src%.computer%..+",
        "^src%.rules%..+",
        "^src%.state%..+",
        "^src%.host%..+",
        "^src%.entry%..+",
      },
    },
    {
      name = "host_no_gameplay_chain",
      description = "host layer must not depend on ui, turn, player, computer, rules, state, or config layers",
      from = { "^src%.host%..+" },
      to = {
        "^src%.ui%..+",
        "^src%.turn%..+",
        "^src%.player%..+",
        "^src%.computer%..+",
        "^src%.rules%..+",
        "^src%.state%..+",
        "^src%.config%..+",
      },
    },
    {
      name = "ui_schema_pure",
      description = "ui schema must stay pure and only depend on ui schema or shared inner modules",
      from = { "^src%.ui%.schema%..+" },
      to = {
        "^src%.ui%.input%..+",
        "^src%.ui%.controllers%..+",
        "^src%.ui%.presenters%..+",
        "^src%.ui%.render%..+",
        "^src%.ui%.widgets%..+",
        "^src%.ui%.stores%..+",
        "^src%.turn%..+",
        "^src%.player%..+",
        "^src%.computer%..+",
        "^src%.rules%..+",
        "^src%.host%..+",
        "^src%.entry%..+",
      },
    },
    {
      name = "presentation_no_game",
      description = "presentation layer must not require src.game.* directly",
      from = { "^src%.presentation%..+" },
      to = { "^src%.game%..+" },
    },
    {
      name = "presentation_input_no_game",
      description = "interaction layer must not require src.game.* directly",
      from = { "^src%.presentation%.input%..+" },
      to = { "^src%.game%..+" },
    },
    {
      name = "presentation_model_no_view",
      description = "presentation model must not depend on presentation view",
      from = { "^src%.presentation%.model%..+" },
      to = { "^src%.presentation%.view%..+" },
    },
    {
      name = "presentation_input_no_runtime",
      description = "presentation input must not depend on presentation runtime directly",
      from = { "^src%.presentation%.input%..+" },
      to = { "^src%.presentation%.runtime%..+" },
    },
    {
      name = "presentation_input_no_view",
      description = "presentation input must not depend on presentation view directly",
      from = { "^src%.presentation%.input%..+" },
      to = { "^src%.presentation%.view%..+" },
    },
    {
      name = "presentation_view_no_input",
      description = "presentation view must stay pure and not depend on presentation input directly",
      from = { "^src%.presentation%.view%..+" },
      to = { "^src%.presentation%.input%..+" },
    },
    {
      name = "presentation_view_no_runtime",
      description = "presentation view must not depend on presentation runtime directly",
      from = { "^src%.presentation%.view%..+" },
      to = { "^src%.presentation%.runtime%..+" },
    },
    {
      name = "presentation_schema_core_only",
      description = "presentation schema must stay pure and only depend on core or schema modules",
      from = { "^src%.presentation%.schema%..+" },
      to = {
        "^src%.presentation%.input%..+",
        "^src%.presentation%.model%..+",
        "^src%.presentation%.runtime%..+",
        "^src%.presentation%.view%..+",
        "^src%.game%..+",
        "^src%.app%..+",
        "^src%.infrastructure%..+",
      },
    },
    {
      name = "core_no_flow",
      description = "core layer must not depend on src.game.flow.* directly",
      from = { "^src%.core%..+" },
      to = { "^src%.game%.flow%..+" },
    },
    {
      name = "core_ports_no_gameplay",
      description = "core runtime contracts must stay gameplay-agnostic",
      from = { "^src%.core%.ports%..+" },
      to = { "^src%.game%.systems%..+", "^src%.game%.flow%..+", "^src%.game%.ports%..+" },
    },
    {
      name = "game_ports_no_flow_local_bundle",
      description = "game ports must stay systems-facing contracts; loop_ports is flow-local",
      from = { "^src%.game%.ports%..+" },
      to = { "^src%.game%.flow%.turn%.loop_ports$" },
    },
    {
      name = "game_core_player_no_flow",
      description = "game core player state must not depend on src.game.flow.* directly",
      from = { "^src%.game%.core%.player$", "^src%.game%.core%.player%..+" },
      to = { "^src%.game%.flow%..+" },
    },
    {
      name = "game_core_player_no_systems",
      description = "game core player state must not depend on src.game.systems.* directly",
      from = { "^src%.game%.core%.player$", "^src%.game%.core%.player%..+" },
      to = { "^src%.game%.systems%..+" },
    },
    {
      name = "systems_no_flow",
      description = "systems layer must not depend on src.game.flow.* directly",
      from = { "^src%.game%.systems%..+" },
      to = { "^src%.game%.flow%..+" },
    },
    {
      name = "systems_no_core_runtime",
      description = "systems layer must not depend on game.core.runtime directly",
      from = { "^src%.game%.systems%..+" },
      to = { "^src%.game%.core%.runtime%..+" },
    },
    {
      name = "scheduler_no_flow",
      description = "scheduler layer must not depend on flow layer directly",
      from = { "^src%.game%.scheduler$", "^src%.game%.scheduler%..+" },
      to = { "^src%.game%.flow%..+" },
    },
    {
      name = "core_runtime_no_runtime_adapters",
      description = "game core runtime must not depend on gameplay runtime adapters directly",
      from = { "^src%.game%.core%.runtime%..+" },
      to = { "^src%.game%.runtime%..+" },
    },
    {
      name = "market_no_land_choice_specs",
      description = "market subsystem must not depend on land choice specs",
      from = { "^src%.game%.systems%.market%..+" },
      to = { "^src%.game%.systems%.land%.choice_specs$" },
    },
    {
      name = "items_no_land_board_utils",
      description = "items subsystem must not depend on land board helpers directly",
      from = { "^src%.game%.systems%.items%..+" },
      to = { "^src%.game%.systems%.land%.board_utils$" },
    },
    {
      name = "items_no_land_rent_resolver",
      description = "items subsystem must not depend on land rent resolver directly",
      from = { "^src%.game%.systems%.items%..+" },
      to = { "^src%.game%.systems%.land%.rent_resolver$" },
    },
  },
}
