return {
  source_roots = { "src" },
  component_rules = {
    { name = "entry", match = { "^src%.entry$", "^src%.entry%..+" }, component = "entry" },
    { name = "host", match = { "^src%.host$", "^src%.host%..+" }, component = "host" },
    { name = "ui", match = { "^src%.ui$", "^src%.ui%..+" }, component = "ui" },
    { name = "turn", match = { "^src%.turn$", "^src%.turn%..+" }, component = "turn" },
    { name = "player", match = { "^src%.player$", "^src%.player%..+" }, component = "player" },
    { name = "computer", match = { "^src%.computer$", "^src%.computer%..+" }, component = "computer" },
    { name = "rules", match = { "^src%.rules$", "^src%.rules%..+" }, component = "rules" },
    { name = "state_access", match = { "^src%.state%.state_access%..+" }, component = "core" },
    { name = "player_state_bridge", match = { "^src%.state%.player_state$" }, component = "game_runtime" },
    { name = "state_root", match = { "^src%.state$", "^src%.state%..+" }, component = "state" },
    { name = "config_root", match = { "^src%.config$", "^src%.config%..+" }, component = "config" },
    { name = "core", match = { "^src%.core%..+" }, component = "core" },
  },
  abstract_rules = {
    { name = "core_ports", match = { "^src%.core%.ports%..+" } },
    { name = "rules_ports", match = { "^src%.rules%.ports%..+" } },
  },
  forbidden_dependency_rules = {
    {
      name = "ui_no_player",
      description = "ui layer must not depend on player modules directly",
      from = { "^src%.ui%..+" },
      to = { "^src%.player%..+" },
    },
    {
      name = "ui_no_computer",
      description = "ui layer must not depend on computer modules directly",
      from = { "^src%.ui%..+" },
      to = { "^src%.computer%..+" },
    },
    {
      name = "ui_no_rules",
      description = "ui layer must not depend on rules modules directly",
      from = { "^src%.ui%..+" },
      to = { "^src%.rules%..+" },
    },
    {
      name = "turn_no_ui",
      description = "turn layer must not depend on ui modules directly",
      from = { "^src%.turn%..+" },
      to = { "^src%.ui%..+" },
    },
    {
      name = "player_no_turn",
      description = "player layer must not depend on turn modules directly",
      from = { "^src%.player%..+" },
      to = { "^src%.turn%..+" },
    },
    {
      name = "player_no_ui",
      description = "player layer must not depend on ui modules directly",
      from = { "^src%.player%..+" },
      to = { "^src%.ui%..+" },
    },
    {
      name = "player_no_host",
      description = "player layer must not depend on host modules directly",
      from = { "^src%.player%..+" },
      to = { "^src%.host%..+", "^src%.entry%..+" },
    },
    {
      name = "computer_no_turn",
      description = "computer layer must not depend on turn modules directly",
      from = { "^src%.computer%..+" },
      to = { "^src%.turn%..+" },
    },
    {
      name = "computer_no_ui",
      description = "computer layer must not depend on ui modules directly",
      from = { "^src%.computer%..+" },
      to = { "^src%.ui%..+" },
    },
    {
      name = "computer_no_host",
      description = "computer layer must not depend on host modules directly",
      from = { "^src%.computer%..+" },
      to = { "^src%.host%..+", "^src%.entry%..+" },
    },
    {
      name = "rules_no_outer_layers",
      description = "rules layer must stay inner and not depend on turn/ui/player/computer/host/entry",
      from = { "^src%.rules%..+" },
      to = {
        "^src%.turn%..+",
        "^src%.ui%..+",
        "^src%.player%..+",
        "^src%.computer%..+",
        "^src%.host%..+",
        "^src%.entry%..+",
      },
    },
    {
      name = "state_no_outer_layers",
      description = "state layer must stay pure and not depend on gameplay, ui, host, or entry layers",
      from = { "^src%.state%..+" },
      to = {
        "^src%.turn%..+",
        "^src%.ui%..+",
        "^src%.player%..+",
        "^src%.computer%..+",
        "^src%.rules%..+",
        "^src%.host%..+",
        "^src%.entry%..+",
      },
    },
    {
      name = "config_no_outer_layers",
      description = "config layer must not depend on gameplay, ui, host, or entry layers",
      from = { "^src%.config%..+" },
      to = {
        "^src%.turn%..+",
        "^src%.ui%..+",
        "^src%.player%..+",
        "^src%.computer%..+",
        "^src%.rules%..+",
        "^src%.state%..+",
        "^src%.host%..+",
        "^src%.entry%..+",
      },
    },
    {
      name = "host_no_gameplay_chain",
      description = "host layer must not depend on ui, turn, player, computer, rules, state, or config layers",
      from = { "^src%.host%..+" },
      to = {
        "^src%.ui%..+",
        "^src%.turn%..+",
        "^src%.player%..+",
        "^src%.computer%..+",
        "^src%.rules%..+",
        "^src%.state%..+",
        "^src%.config%..+",
      },
    },
    {
      name = "ui_schema_pure",
      description = "ui schema must stay pure and only depend on ui schema or shared inner modules",
      from = { "^src%.ui%.schema%..+" },
      to = {
        "^src%.ui%.input%..+",
        "^src%.ui%.controllers%..+",
        "^src%.ui%.presenters%..+",
        "^src%.ui%.render%..+",
        "^src%.ui%.widgets%..+",
        "^src%.ui%.stores%..+",
        "^src%.turn%..+",
        "^src%.player%..+",
        "^src%.computer%..+",
        "^src%.rules%..+",
        "^src%.host%..+",
        "^src%.entry%..+",
      },
    },
  },
}
